name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    id: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build -v ./...


  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Trigger Slackbot
      run: go run slackNotification.go https://github.com/avocadohooman/Go-Slackbot SUCCESS githubRun:${{ github.run_number }} github.event.commits.*.message


  buildFailed:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build failed
      if: failure() && steps.build.outcome == 'failure'
      run: go run slackNotification.go https://github.com/avocadohooman/Go-Slackbot FAILED githubRun:${{ github.run_number }} github.event.commits.*.message
  