name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      id: build
      run: go build -v ./...


  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Trigger Slackbot
      run: go run slackNotification.go https://github.com/avocadohooman/Go-Slackbot SUCCESS githubRun:${{ github.run_number }} "${{ github.event.head_commit.message }}"
      env:
        SLACK_OAUTH_TOKEN: ${{secrets.SLACK_OAUTH_TOKEN}}


  buildFailed:
    needs: [build]    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build failed
      if: failure() && steps.build.outcome == 'failure'
      run: go run slackNotification.go https://github.com/avocadohooman/Go-Slackbot FAILED githubRun:${{ github.run_number }} "${{ github.event.head_commit.message }}"
  